name: Otomatik Tweet

on:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 7 * * *'
    - cron: '0 9 * * *'
    - cron: '0 11 * * *'
    - cron: '0 13 * * *'
    - cron: '0 15 * * *'
    - cron: '0 17 * * *'
    - cron: '30 18 * * *'
    - cron: '30 19 * * *'
    - cron: '30 20 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install tweepy
      - run: python tweet.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
